spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_jwt_service
    username: postgres
    password: HelloToday
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
